protocols = imap
listen = *, ::
auth_mechanisms = plain login
mail_driver = maildir
mail_home = /home/%{user | username}
mail_path = %{home}/Maildir
mail_inbox_path = %{home}/Maildir

ssl_server {
  cert_file = /etc/home-vpn-mail/tls/mail.crt
  key_file = /etc/home-vpn-mail/tls/mail.key
}

service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}
