[Service]
PrivateDevices=no
ProtectHostname=no
ProtectKernelTunables=no
ProtectKernelModules=no
ProtectKernelLogs=no
ProtectControlGroups=no
ProtectClock=no
ProtectSystem=no
ProcSubset=all
RestrictNamespaces=no
LockPersonality=no

